version: '3'
services:
  dev:
    build: .
    environment:
      - KBC_URL=${STORAGE_API_URL}
      - KBC_TOKEN=${STORAGE_API_TOKEN}
      - CLIENT_ID
      - CLIENT_SECRET
      - ACCESS_TOKEN
      - REFRESH_TOKEN
    volumes:
      - ./:/code
      - ./data:/data
